[project]
name = "spherefactor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pytest>=8.4.1",
    "scipy>=1.16.0",
    "soundfile>=0.13.1",
]
